### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by MyNewBie** [jossalgon/teamSpeakTelegram#4]
1# is it possible add button if users click on it they connect to teamspeak server ?
2# is it possible add ability for send msg to teamspeak from telegram or send poke to all ?

**Comment by jossalgon** [comment]
Good ideas, I'll be on it :+1:

**Comment by jossalgon** [comment]
Is this what you meant? @MyNewBie

**Comment by MyNewBie** [comment]
yes that exactly what i want xD great job

edit* : send global message and global poke .

**Comment by jossalgon** [comment]
Great, but what do you mean with the "edit*"? Also include a global poke?

**Comment by MyNewBie** [comment]
I forget tell you add global poke then I edit my last comment . sorry

**Comment by MyNewBie** [comment]
I have no idea why I get this error : https://pastebin.com/QrWKp8xE

**Comment by jossalgon** [comment]
I'll include an individual and global poke at next update.
Try uninstalling and installing like I mention at #5

**Comment by MyNewBie** [comment]
ahhhh , Its annoying `/usr/local/bin/python3: Error while finding spec for 'teamSpeakTelegram.__main__' (<class 'ImportError'>: No module named 'future'); 'teamSpeakTelegram' is a package and cannot be directly executed`
I did `pip3 install future` bot still this error .

**Comment by jossalgon** [comment]
If you have too many problems with python dependencies, check out virtualenv.

**Comment by MyNewBie** [comment]
ok now seems work i don't know how i did this :D but work now the only error is `/usr/local/lib/python3.6/site-packages/pymysql/cursors.py:103: Warning: (1050, "Table 'Invitations' already exists")
  return self._nextset(False)`

**Comment by jossalgon** [comment]
This isn't an error, just a warning that should not appear because the table won't be created if it does not exist. Everything is correct.

**Comment by MyNewBie** [comment]
yes can you please update README.md  ?

**Comment by jossalgon** [comment]
Update with what? I updated with the /gm command at the last commit.
Please try to detail comments and issue titles to be more effective, thanks.

**Comment by MyNewBie** [comment]
xD ok nothing , you great nice work.
thanks

**Comment by jossalgon** [comment]
Haha ok thanks :smile: 
I'll close this issue and I hope to add poke in the next days.

**Comment by MyNewBie** [comment]
hey sorry im here again xD , I created share link its like button for me but when I click on button and select another group for share , it show as a link not button , I want to know is it possible to show it as button too or not ? and I didn't get /mention whats this for ? and I think bot cant write anything on database caz TsUsers table is empty for me and I added user manually .

**Comment by jossalgon** [comment]
Hey haha no problem, nice to read an issue again xD

Share link is a link when shared because that's the easy way, if I implement it as a button, it would be necessary that in addition you (and every person that uses my code) have to give special permissions to the bot by BotFather to make use of inline mode and this could be confusing. So, I decided to use better a shared link.

Also, remember that links generated can only be used once, they are unique. You should generate one link per telegram user.

/mention is a way activate a "notification", when it's used at a telegram group you should receive at private a forwarded messsage if that contains @flandas. Example: "anyone want play sth @flandas?" and this will be forwarded to every person that has /mention activated.
PD: this is a request from some friends.
